# -*- coding: utf-8 -*-
"""Learning engine protocols — advisory only, never self-modifying."""
from __future__ import annotations

from typing import Any, Protocol


class LessonRepositoryProtocol(Protocol):
    def save(self, lesson: dict[str, Any]) -> str: ...
    def load(self, lesson_id: str) -> dict[str, Any] | None: ...
    def list_all(self) -> list[dict[str, Any]]: ...
    def update_status(self, lesson_id: str, status: str) -> bool: ...


class LearningHistoryProtocol(Protocol):
    def save_proposal(self, proposal: dict[str, Any]) -> str: ...
    def save_hypothesis(self, hypothesis: dict[str, Any]) -> str: ...
    def save_report(self, report: dict[str, Any]) -> str: ...
    def list_proposals(self) -> list[dict[str, Any]]: ...
    def list_hypotheses(self) -> list[dict[str, Any]]: ...
    def list_reports(self) -> list[dict[str, Any]]: ...


class ReflectionEngineProtocol(Protocol):
    def reflect(self, *, scope: dict[str, Any] | None = None) -> dict[str, Any]: ...


class PatternDetectorProtocol(Protocol):
    def detect(self, evaluations: list[dict[str, Any]],
               context: dict[str, Any] | None = None) -> list[dict[str, Any]]: ...


class LessonGeneratorProtocol(Protocol):
    def generate(self, patterns: list[dict[str, Any]],
                 evaluations: list[dict[str, Any]]) -> list[dict[str, Any]]: ...
