# -*- coding: utf-8 -*-
"""Predictive modeling protocols."""
from __future__ import annotations

from typing import Any, Protocol

from .prediction import PredictionResult
from .trainer import ModelArtifact, TrainingConfig


class PredictiveModelProtocol(Protocol):
    def train(self, X: list[list[float]], y: list[float | int], **kwargs: Any) -> Any: ...
    def predict(self, X: list[list[float]], **kwargs: Any) -> list[float]: ...
    def save(self, path: str) -> None: ...


class TrainerProtocol(Protocol):
    def train(self, rows: list[dict[str, Any]], config: TrainingConfig) -> ModelArtifact: ...


class PredictiveEngineProtocol(Protocol):
    def train(self, rows: list[dict[str, Any]], config: TrainingConfig, **kwargs: Any) -> ModelArtifact: ...
    def evaluate(self, model_id: str, rows: list[dict[str, Any]]) -> dict[str, Any]: ...
    def predict(self, model_id: str, feature_vector: dict[str, float | int]) -> PredictionResult: ...
    def list_models(self) -> list[dict[str, Any]]: ...
    def load_model(self, model_id: str) -> ModelArtifact: ...
    def registry(self, **kwargs: Any) -> list[dict[str, Any]]: ...
