# -*- coding: utf-8 -*-
"""Orchestration protocols."""
from __future__ import annotations

from typing import Any, Protocol

from .execution_context import ExecutionContext
from .result import MarketAnalysis


class StageProtocol(Protocol):
    name: str
    def prepare(self, ctx: ExecutionContext) -> list[str]: ...
    def execute(self, ctx: ExecutionContext) -> dict[str, Any]: ...
    def validate(self, output: dict[str, Any]) -> list[str]: ...
    def cleanup(self, ctx: ExecutionContext) -> None: ...


class OrchestratorProtocol(Protocol):
    def run(self, **kwargs: Any) -> MarketAnalysis: ...
    def status(self, analysis_id: str) -> dict[str, Any] | None: ...


class AnalysisServiceProtocol(Protocol):
    def analyze_market(self, **kwargs: Any) -> MarketAnalysis: ...
    def analyze_symbol(self, symbol: str, **kwargs: Any) -> MarketAnalysis: ...
    def analyze_strategy(self, strategy_id: str, **kwargs: Any) -> MarketAnalysis: ...
    def status(self, analysis_id: str) -> dict[str, Any] | None: ...
